name: Generate TagInfo JSON
on:
  push:
    branches:
      - master

jobs:
  generate-taginfo-json:
    name: Generate TagInfo JSON
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: sudo snap install kotlin --channel=1.4/stable --classic
      - run: kotlinc -script -Xplugin=/snap/kotlin/current/lib/kotlinx-serialization-compiler-plugin.jar .github/generate-quest-metadata.main.kts -- --task json
      - uses: actions/upload-artifact@v2
        with:
          name: taginfo.json
          path: ./taginfo.json
